version: "3.7"

services:

  nginx:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_nginx
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - 80:80
      - 8080:8080

  php:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php
    build:
      context: ./.docker/php${PHP_VER}-dev
      args:
        PHP_VER: ${PHP_VER}
    env_file:
      - .env
    ports:
      - "9000:9000"
    environment:
      PHP_IDE_CONFIG: serverName=docker
    #user: 1000:1000
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./:/app:rw
    working_dir: /app

  mysql:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_mysql
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql/
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    env_file:
      - .env

volumes:
  db_data:
